# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Craft Along with Me
email: hello@craftalong.me
description: > # this means to ignore newlines until "baseurl:"
  Craft Along with Me - you don't have to do it alone.
baseurl: "" # the subpath of your site, e.g. /blog
url: "craftalong.me" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
